[package]
name = "socialblock"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
anyhow = "1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
notify = "8.2.0"