[meta.facebook]
domains = [
  "facebook.com",
  "*.facebook.com",
]

[meta.instagram]
domains = [
  "instagram.com",
  "*.instagram.com",
]

[tiktok]
domains = [
  "tiktok.com",
  "*.tiktok.com",
  "*.tiktokcdn.com",
]

[schedule]
enable = true
block = "Mon..Fri 08:00"
unblock = "Mon..Fri 18:00"
